FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY output/training_data ./output/training_data
COPY output/models ./output/models

CMD ["python", "src/retraining_pipeline.py"]